

DB_HOST = "senda-cafe-db.cfeiae0wyoyd.us-east-2.rds.amazonaws.com"
DB_NAME = "senda_cafe"
DB_USER = "admin_senda_cafe"
DB_PASSWORD = "Sendacafe2025"
DB_PORT = "5432"


SENDGRID_API_KEY = "ALERTA DE STOCK"
ALERT_EMAIL_TO = "fernandomdq12@gmail.com , ferrobles90@hotmail.com"
ALERT_EMAIL_FROM = "fernando.robles.mdq@gmail.com"
